
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vizug
 */
public class VehicleDlg extends javax.swing.JDialog {

    Vehicle v = null;
    boolean ok = false;

    /**
     * Creates new form VehicleDlg
     */
    public VehicleDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        for (Vehicle.VehicleType value : Vehicle.VehicleType.values()) {
            cmbType.addItem(value);
        }
    }

    public Vehicle getV() {
        return v;
    }

    public boolean isOk() {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMarke = new javax.swing.JLabel();
        tfMarke = new javax.swing.JTextField();
        lbBJ = new javax.swing.JLabel();
        tfBJ = new javax.swing.JTextField();
        lbKM = new javax.swing.JLabel();
        tfKM = new javax.swing.JTextField();
        lbTyp = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        cbClimate = new javax.swing.JCheckBox();
        cbHeatedSeats = new javax.swing.JCheckBox();
        btOK = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        lbMarke.setText("Marke:");
        getContentPane().add(lbMarke);

        tfMarke.setText("BMW");
        getContentPane().add(tfMarke);

        lbBJ.setText("Baujahr:");
        getContentPane().add(lbBJ);

        tfBJ.setText("2014");
        getContentPane().add(tfBJ);

        lbKM.setText("KM:");
        getContentPane().add(lbKM);

        tfKM.setText("23000");
        getContentPane().add(tfKM);

        lbTyp.setText("Typ:");
        getContentPane().add(lbTyp);

        getContentPane().add(cmbType);

        cbClimate.setText("Klima");
        getContentPane().add(cbClimate);

        cbHeatedSeats.setText("Sitzheizung");
        getContentPane().add(cbHeatedSeats);

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });
        getContentPane().add(btOK);

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        ok = false;
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        ArrayList extras = null;
        //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy");
        //LocalDate date = LocalDate.parse(tfBJ.getText(),dtf);
        if (cmbType.getSelectedItem().equals(Vehicle.VehicleType.PKW)) {
            if (cbClimate.isSelected()) {
                extras.add(new Klima(200.0));
            }
            if (cbHeatedSeats.isSelected()) {
                extras.add(new Sitzheizung(150.0));
            }
            v = new Car(tfMarke.getText(), tfBJ.getText(),
                    Double.parseDouble(tfKM.getText()), extras);
        } else {
            v = new Truck(tfMarke.getText(), tfBJ.getText(),
                    Double.parseDouble(tfKM.getText()), extras);
        }

        ok = true;
        this.dispose();
    }//GEN-LAST:event_btOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VehicleDlg dialog = new VehicleDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOK;
    private javax.swing.JCheckBox cbClimate;
    private javax.swing.JCheckBox cbHeatedSeats;
    private javax.swing.JComboBox<Vehicle.VehicleType> cmbType;
    private javax.swing.JLabel lbBJ;
    private javax.swing.JLabel lbKM;
    private javax.swing.JLabel lbMarke;
    private javax.swing.JLabel lbTyp;
    private javax.swing.JTextField tfBJ;
    private javax.swing.JTextField tfKM;
    private javax.swing.JTextField tfMarke;
    // End of variables declaration//GEN-END:variables
}
